In [1]:
import pandas as pd
import os

base = "/home/nevado/BigData_UPAO/osiptel_staging"
archivos = {
    "2.1 Internet Fijo":
        f"{base}/internet_fijo_2_1/2.1 CONEXIONES DE INTERNET FIJO.xlsx",
    "2.2 Fibra Óptica":
        f"{base}/fibra_optica_2_2/2.2. CONEXIONES DE INTERNET FIJO DE FIBRA ÓPTICA.xlsx",
    "2.3 Internet Fijo Distrital":
        f"{base}/internet_fijo_distrital_2_3/2.3 CONEXIONES DE INTERNET FIJO POR DISTRITO.xlsx",
    "4.1 Telefonía Fija":
        f"{base}/telefonia_fija_4_1/4.1. LÍNEAS FIJAS DE ABONADO EN SERVICIO.xlsx"
}

In [2]:
for nombre, ruta in archivos.items():
    xls = pd.ExcelFile(ruta)
    print("=" * 70)
    print(nombre)
    print("Archivo:", os.path.basename(ruta))
    print("Tamaño:", round(os.path.getsize(ruta) / 1024 / 1024, 2), "MB")
    print("Hojas:", xls.sheet_names)

======================================================================
2.1 Internet Fijo
Archivo: 2.1 CONEXIONES DE INTERNET FIJO.xlsx
Tamaño: 7.18 MB
Hojas: ['Dataset', 'Diccionario']
======================================================================
2.2 Fibra Óptica
Archivo: 2.2. CONEXIONES DE INTERNET FIJO DE FIBRA ÓPTICA.xlsx
Tamaño: 0.03 MB
Hojas: ['Dataset', 'Diccionario']
======================================================================
2.3 Internet Fijo Distrital
Archivo: 2.3 CONEXIONES DE INTERNET FIJO POR DISTRITO.xlsx
Tamaño: 5.33 MB
Hojas: ['Dataset', 'Diccionario']
======================================================================
4.1 Telefonía Fija
Archivo: 4.1. LÍNEAS FIJAS DE ABONADO EN SERVICIO.xlsx
Tamaño: 1.41 MB
Hojas: ['Dataset', 'Diccionario']

In [3]:
ruta_21 = archivos["2.1 Internet Fijo"]
vista_21 = pd.read_excel(
    ruta_21,
    sheet_name="Dataset",
    header=None,
    nrows=10
)
vista_21

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,DATASET: CONEXIONES DE INTERNET FIJO,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Mes,Empresa,Tecnologia,Segmento,Departamento,Rango Velocidad de Bajada (nominal),Conexiones
4,NaN,1999-12-01 00:00:00,NaN,1) Dial-Up Fijo,No identificada,NaN,NaN,120014
5,NaN,2000-12-01 00:00:00,NaN,1) Dial-Up Fijo,No identificada,NaN,NaN,130560
6,NaN,2000-12-01 00:00:00,NaN,2) xDSL,No identificada,NaN,NaN,32
7,NaN,2000-12-01 00:00:00,NaN,3) Cablemodem,No identificada,NaN,NaN,788
8,NaN,2001-12-01 00:00:00,NaN,1) Dial-Up Fijo,Comercial,NaN,NaN,3264
9,NaN,2001-12-01 00:00:00,NaN,1) Dial-Up Fijo,Residencial,NaN,NaN,139371

In [4]:
diccionario_21 = pd.read_excel(
    ruta_21,
    sheet_name="Diccionario",
    header=None
)
diccionario_21.head(15)

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,ATRIBUTO,DESCRIPCIÓN,TIPO DE DATO
3,NaN,Mes,Mes al que corresponde el dato reportado.,Fecha: AAAA-MM-DD
4,NaN,Empresa,Nombre (razón social) de la empresa operadora ...,Cadena
5,NaN,Tecnología,Tecnología de acceso por medio del cual se pre...,Cadena
6,NaN,Segmento,Se refiere al segmento al que pertenece la con...,Cadena
7,NaN,Departamento,Departamento donde se encuentra instalada la c...,Cadena
8,NaN,Rango Velocidad de Bajada (nominal),Rango en el que se encuentra la velocidad de b...,Alfanumérico
9,NaN,Conexiones,"Número de conexiones en servicio, al cierre de...",Numérico
10,NaN,Fuente: Norma de Requerimientos de Información...,NaN,NaN
11,NaN,"Información a marzo de 2026, actualizada al 15...",NaN,NaN
12,NaN,Nota general: Información remitida por las emp...,NaN,NaN
13,NaN,"“Otras tecnologías” incluye GSM, LTE, VSAT, SC...",NaN,NaN
14,NaN,"A partir de abril de 2025, Telefónica del Perú...",NaN,NaN

In [5]:
df_21 = pd.read_excel(
    ruta_21,
    sheet_name="Dataset",
    header=3
)
df_21.head()

,Unnamed: 0,Mes,Empresa,Tecnologia,Segmento,Departamento,Rango Velocidad de Bajada (nominal),Conexiones
0,NaN,1999-12-01,NaN,1) Dial-Up Fijo,No identificada,NaN,NaN,120014
1,NaN,2000-12-01,NaN,1) Dial-Up Fijo,No identificada,NaN,NaN,130560
2,NaN,2000-12-01,NaN,2) xDSL,No identificada,NaN,NaN,32
3,NaN,2000-12-01,NaN,3) Cablemodem,No identificada,NaN,NaN,788
4,NaN,2001-12-01,NaN,1) Dial-Up Fijo,Comercial,NaN,NaN,3264

In [6]:
df_21 = df_21.loc[:, ~df_21.columns.astype(str).str.startswith("Unnamed")]
df_21.head()

,Mes,Empresa,Tecnologia,Segmento,Departamento,Rango Velocidad de Bajada (nominal),Conexiones
0,1999-12-01,NaN,1) Dial-Up Fijo,No identificada,NaN,NaN,120014
1,2000-12-01,NaN,1) Dial-Up Fijo,No identificada,NaN,NaN,130560
2,2000-12-01,NaN,2) xDSL,No identificada,NaN,NaN,32
3,2000-12-01,NaN,3) Cablemodem,No identificada,NaN,NaN,788
4,2001-12-01,NaN,1) Dial-Up Fijo,Comercial,NaN,NaN,3264

In [7]:
print("Filas:", df_21.shape[0])
print("Columnas:", df_21.shape[1])
print("\nColumnas:")
for columna in df_21.columns:
    print("-", columna)
print("\nTipos de datos:")
print(df_21.dtypes)

Filas: 141106
Columnas: 7

Columnas:
- Mes
- Empresa
- Tecnologia
- Segmento
- Departamento
- Rango Velocidad de Bajada (nominal)
- Conexiones

Tipos de datos:
Mes                                    datetime64[ns]
Empresa                                        object
Tecnologia                                     object
Segmento                                       object
Departamento                                   object
Rango Velocidad de Bajada (nominal)            object
Conexiones                                      int64
dtype: object

In [8]:
print("Fecha mínima:", df_21["Mes"].min())
print("Fecha máxima:", df_21["Mes"].max())
print("\nValores nulos:")
print(df_21.isnull().sum())

Fecha mínima: 1999-12-01 00:00:00
Fecha máxima: 2026-03-01 00:00:00

Valores nulos:
Mes                                        0
Empresa                                   91
Tecnologia                                 0
Segmento                                   0
Departamento                             201
Rango Velocidad de Bajada (nominal)    13029
Conexiones                                 0
dtype: int64

In [9]:
print("Duplicados exactos:", df_21.duplicated().sum())

Duplicados exactos: 2486

In [11]:
duplicados_21 = df_21[df_21.duplicated(keep=False)]
print("Total de filas involucradas en duplicados:", len(duplicados_21))
duplicados_21.sort_values(
    ["Mes", "Tecnologia", "Segmento"]
).head(20)

Total de filas involucradas en duplicados: 3807

,Mes,Empresa,Tecnologia,Segmento,Departamento,Rango Velocidad de Bajada (nominal),Conexiones
204,2012-12-01,AMERICA MOVIL PERU S.A.C.,2) xDSL,Comercial,LIMA Y CALLAO,NaN,4
205,2012-12-01,AMERICA MOVIL PERU S.A.C.,2) xDSL,Comercial,LIMA Y CALLAO,NaN,4
342,2012-12-01,TELEFONICA DEL PERU S.A.A.,3) Cablemodem,Residencial,OTRAS REGIONES,NaN,1
343,2012-12-01,TELEFONICA DEL PERU S.A.A.,3) Cablemodem,Residencial,OTRAS REGIONES,NaN,1
246,2012-12-01,AMERICA MOVIL PERU S.A.C.,7) Otras Tecnologías,Comercial,OTRAS REGIONES,NaN,1
247,2012-12-01,AMERICA MOVIL PERU S.A.C.,7) Otras Tecnologías,Comercial,OTRAS REGIONES,NaN,1
262,2012-12-01,AMERICATEL PERU S.A.,7) Otras Tecnologías,Comercial,LIMA Y CALLAO,NaN,5
263,2012-12-01,AMERICATEL PERU S.A.,7) Otras Tecnologías,Comercial,LIMA Y CALLAO,NaN,5
274,2012-12-01,COMPAÑIA DE COMERCIO GLOBAL S.A.C.,7) Otras Tecnologías,Comercial,LIMA Y CALLAO,NaN,3
275,2012-12-01,COMPAÑIA DE COMERCIO GLOBAL S.A.C.,7) Otras Tecnologías,Comercial,LIMA Y CALLAO,NaN,3
366,2013-03-01,AMERICA MOVIL PERU S.A.C.,2) xDSL,Comercial,LIMA Y CALLAO,NaN,4
367,2013-03-01,AMERICA MOVIL PERU S.A.C.,2) xDSL,Comercial,LIMA Y CALLAO,NaN,4
504,2013-03-01,TELEFONICA DEL PERU S.A.A.,3) Cablemodem,Residencial,OTRAS REGIONES,NaN,1
505,2013-03-01,TELEFONICA DEL PERU S.A.A.,3) Cablemodem,Residencial,OTRAS REGIONES,NaN,1
424,2013-03-01,AMERICATEL PERU S.A.,7) Otras Tecnologías,Comercial,LIMA Y CALLAO,NaN,5
425,2013-03-01,AMERICATEL PERU S.A.,7) Otras Tecnologías,Comercial,LIMA Y CALLAO,NaN,5
458,2013-03-01,GILAT TO HOME PERU S.A.,7) Otras Tecnologías,Residencial,LIMA Y CALLAO,NaN,1
459,2013-03-01,GILAT TO HOME PERU S.A.,7) Otras Tecnologías,Residencial,LIMA Y CALLAO,NaN,1
509,2013-03-01,TELEFONICA DEL PERU S.A.A.,7) Otras Tecnologías,Residencial,OTRAS REGIONES,NaN,10
510,2013-03-01,TELEFONICA DEL PERU S.A.A.,7) Otras Tecnologías,Residencial,OTRAS REGIONES,NaN,10

In [13]:
for columna in [
    "Empresa",
    "Tecnologia",
    "Segmento",
    "Departamento",
    "Rango Velocidad de Bajada (nominal)"
]:
    print(f"{columna}: {df_21[columna].nunique()} valores únicos")

Empresa: 161 valores únicos
Tecnologia: 7 valores únicos
Segmento: 3 valores únicos
Departamento: 28 valores únicos
Rango Velocidad de Bajada (nominal): 14 valores únicos

In [14]:
df_21.tail()

,Mes,Empresa,Tecnologia,Segmento,Departamento,Rango Velocidad de Bajada (nominal),Conexiones
141101,2026-03-01,WI-NET TELECOM S.A.C.,5) Fibra Óptica,Residencial,PIURA,j) 50 Mbps <= BW < 100 Mbps,711
141102,2026-03-01,WI-NET TELECOM S.A.C.,5) Fibra Óptica,Residencial,PIURA,k) 100 Mbps <= BW < 200 Mbps,3406
141103,2026-03-01,WI-NET TELECOM S.A.C.,5) Fibra Óptica,Residencial,PIURA,l) 200 Mbps <= BW < 500 Mbps,19673
141104,2026-03-01,WI-NET TELECOM S.A.C.,5) Fibra Óptica,Residencial,PIURA,m) 500 Mbps <= BW < 1000 Mbps,3826
141105,2026-03-01,WI-NET TELECOM S.A.C.,5) Fibra Óptica,Residencial,PIURA,n) BW >= 1000 Mbps,3272

In [15]:
ruta_22 = archivos["2.2 Fibra Óptica"]
vista_22 = pd.read_excel(
    ruta_22,
    sheet_name="Dataset",
    header=None,
    nrows=10
)
vista_22

,0,1,2,3,4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,DATASET: CONEXIONES DE INTERNET FIJO DE FIBRA ...,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,Mes,Empresa,Región,Conexiones
4,NaN,2015-12-01 00:00:00,AGUSTINA SERVICIOS GENERALES S.A.C.,Otros departamentos,120
5,NaN,2015-12-01 00:00:00,AMERICA MOVIL PERU S.A.C.,Lima y Callao,1733
6,NaN,2015-12-01 00:00:00,AMERICA MOVIL PERU S.A.C.,Otros departamentos,380
7,NaN,2015-12-01 00:00:00,AMERICATEL PERU S.A.,Lima y Callao,87
8,NaN,2015-12-01 00:00:00,AMERICATEL PERU S.A.,Otros departamentos,3
9,NaN,2015-12-01 00:00:00,CIRION TECHNOLOGIES PERU S.A. (ANTES CENTURYLI...,Lima y Callao,310

In [16]:
diccionario_22 = pd.read_excel(
    ruta_22,
    sheet_name="Diccionario",
    header=None
)
diccionario_22.head(15)

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,ATRIBUTO,DESCRIPCIÓN,TIPO DE DATO
3,NaN,Mes,Mes al que corresponde el dato reportado.,Fecha: AAAA-MM-DD
4,NaN,Empresa,Nombre (razón social) de la empresa operadora ...,Cadena
5,NaN,Región,"Región (""Lima y Callao"" u ""Otros departamentos...",Cadena
6,NaN,Conexiones,"Número de conexiones en servicio, al cierre de...",Numérico
7,NaN,"Información a diciembre de 2022, actualizada a...",NaN,NaN
8,NaN,Hay algunas empresas que reportaron conexiones...,NaN,NaN
9,NaN,Nota general: Información remitida por las emp...,NaN,NaN

In [17]:
df_22 = pd.read_excel(
    ruta_22,
    sheet_name="Dataset",
    header=3
)
df_22 = df_22.loc[:, ~df_22.columns.astype(str).str.startswith("Unnamed")]
df_22.head()

,Mes,Empresa,Región,Conexiones
0,2015-12-01,AGUSTINA SERVICIOS GENERALES S.A.C.,Otros departamentos,120
1,2015-12-01,AMERICA MOVIL PERU S.A.C.,Lima y Callao,1733
2,2015-12-01,AMERICA MOVIL PERU S.A.C.,Otros departamentos,380
3,2015-12-01,AMERICATEL PERU S.A.,Lima y Callao,87
4,2015-12-01,AMERICATEL PERU S.A.,Otros departamentos,3

In [18]:
print("Filas:", df_22.shape[0])
print("Columnas:", df_22.shape[1])
print("\nColumnas:")
for columna in df_22.columns:
    print("-", columna)
print("\nTipos de datos:")
print(df_22.dtypes)

Filas: 868
Columnas: 4

Columnas:
- Mes
- Empresa
- Región
- Conexiones

Tipos de datos:
Mes           datetime64[ns]
Empresa               object
Región                object
Conexiones             int64
dtype: object

In [19]:
print("Fecha mínima:", df_22["Mes"].min())
print("Fecha máxima:", df_22["Mes"].max())
print("\nValores nulos:")
print(df_22.isnull().sum())

Fecha mínima: 2015-12-01 00:00:00
Fecha máxima: 2022-12-01 00:00:00

Valores nulos:
Mes           0
Empresa       0
Región        0
Conexiones    0
dtype: int64

In [20]:
print("Duplicados exactos:", df_22.duplicated().sum())

Duplicados exactos: 0

In [21]:
df_22.tail()

,Mes,Empresa,Región,Conexiones
863,2022-12-01,WOW TEL S.A.C.,Otros departamentos,123083
864,2022-12-01,YACHAY TELECOMUNICACIONES S.A.C,Lima y Callao,202
865,2022-12-01,YACHAY TELECOMUNICACIONES S.A.C,Otros departamentos,82
866,2022-12-01,GLOBAL FIBER PERU S.A.C.,Lima y Callao,24
867,2022-12-01,GLOBAL FIBER PERU S.A.C.,Otros departamentos,720

In [22]:
ruta_23 = archivos["2.3 Internet Fijo Distrital"]
vista_23 = pd.read_excel(
    ruta_23,
    sheet_name="Dataset",
    header=None,
    nrows=10
)
vista_23

,0,1,2,3,4,5,6,7,8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Conexiones en servicio de Internet fijo por em...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Periodo,Empresa,Departamento,Provincia,Distrito,Tecnología,Segmento,Conexiones
4,NaN,2023-03-01 00:00:00,AGUSTINA SERVICIOS GENERALES S.A.C.,LA LIBERTAD,CHEPEN,CHEPEN,5) Fibra Óptica,Residencial,144
5,NaN,2023-03-01 00:00:00,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BAGUA,BAGUA,6) Otras Tecnologías,Residencial,46
6,NaN,2023-03-01 00:00:00,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BAGUA,IMAZA,6) Otras Tecnologías,Residencial,12
7,NaN,2023-03-01 00:00:00,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BAGUA,LA PECA,6) Otras Tecnologías,Residencial,1
8,NaN,2023-03-01 00:00:00,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BONGARA,JAZAN,6) Otras Tecnologías,Residencial,1
9,NaN,2023-03-01 00:00:00,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BONGARA,VALERA,6) Otras Tecnologías,Residencial,1

In [23]:
diccionario_23 = pd.read_excel(
    ruta_23,
    sheet_name="Diccionario",
    header=None
)
diccionario_23.head(20)

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,ATRIBUTO,DESCRIPCIÓN,TIPO DE DATO
3,NaN,Empresa,Nombre (razón social) de la empresa operadora ...,Cadena
4,NaN,Departamento,Departamento donde se encuentra instalada la c...,Cadena
5,NaN,Provincia,Provincia donde se encuentra instalada la cone...,Cadena
6,NaN,Distrito,Distrito donde se encuentra instalada la conex...,Cadena
7,NaN,Tecnología,Tecnología de acceso por medio del cual se pre...,Cadena
8,NaN,Segmento,Se refiere al segmento al que pertenece la con...,Cadena
9,NaN,Conexiones,"Número de conexiones en servicio, al cierre de...",Numérico
10,NaN,"Información a diciembre de 2025, actualizada a...",NaN,NaN
11,NaN,"Nota: “Otras tecnologías” incluye GSM, LTE, VS...",NaN,NaN
12,NaN,Información remitida por las empresas operador...,NaN,NaN
13,NaN,"La información correspondiente a Departamento,...",NaN,NaN
14,NaN,"A partir de abril de 2025, Telefónica del Perú...",NaN,NaN

In [25]:
df_23 = pd.read_excel(
    ruta_23,
    sheet_name="Dataset",
    header=3
)
df_23 = df_23.loc[:, ~df_23.columns.astype(str).str.startswith("Unnamed")]
df_23.head()

,Periodo,Empresa,Departamento,Provincia,Distrito,Tecnología,Segmento,Conexiones
0,2023-03-01,AGUSTINA SERVICIOS GENERALES S.A.C.,LA LIBERTAD,CHEPEN,CHEPEN,5) Fibra Óptica,Residencial,144
1,2023-03-01,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BAGUA,BAGUA,6) Otras Tecnologías,Residencial,46
2,2023-03-01,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BAGUA,IMAZA,6) Otras Tecnologías,Residencial,12
3,2023-03-01,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BAGUA,LA PECA,6) Otras Tecnologías,Residencial,1
4,2023-03-01,AMERICA MOVIL PERU S.A.C.,AMAZONAS,BONGARA,JAZAN,6) Otras Tecnologías,Residencial,1

In [26]:
print("Filas:", df_23.shape[0])
print("Columnas:", df_23.shape[1])
print("\nColumnas:")
for columna in df_23.columns:
    print("-", columna)
print("\nTipos de datos:")
print(df_23.dtypes)

Filas: 157310
Columnas: 8

Columnas:
- Periodo
- Empresa
- Departamento
- Provincia
- Distrito
- Tecnología
- Segmento
- Conexiones

Tipos de datos:
Periodo         datetime64[ns]
Empresa                 object
Departamento            object
Provincia               object
Distrito                object
Tecnología              object
Segmento                object
Conexiones               int64
dtype: object

In [27]:
print("Fecha mínima:", df_23["Periodo"].min())
print("Fecha máxima:", df_23["Periodo"].max())
print("\nValores nulos:")
print(df_23.isnull().sum())

Fecha mínima: 2023-03-01 00:00:00
Fecha máxima: 2025-12-12 00:00:00

Valores nulos:
Periodo         0
Empresa         0
Departamento    0
Provincia       0
Distrito        0
Tecnología      0
Segmento        0
Conexiones      0
dtype: int64

In [28]:
print("Duplicados exactos:", df_23.duplicated().sum())

Duplicados exactos: 0

In [32]:
for columna in [
    "Empresa",
    "Departamento",
    "Provincia",
    "Distrito",
    "Segmento"
]:
    print(f"{columna}: {df_23[columna].nunique()} valores únicos")

Empresa: 116 valores únicos
Departamento: 26 valores únicos
Provincia: 198 valores únicos
Distrito: 1733 valores únicos
Segmento: 4 valores únicos

In [33]:
df_23.tail()

,Periodo,Empresa,Departamento,Provincia,Distrito,Tecnología,Segmento,Conexiones
157305,2025-12-01,INTERNEXA PERU S.A.,PIURA,TALARA,PARIÑAS,5) Fibra Óptica,Comercial,2
157306,2025-12-01,INTERNEXA PERU S.A.,PUNO,AZANGARO,AZANGARO,5) Fibra Óptica,Comercial,1
157307,2025-12-01,INTERNEXA PERU S.A.,TACNA,TACNA,TACNA,6) Otras Tecnologías,Comercial,2
157308,2025-12-01,INTERNEXA PERU S.A.,TUMBES,CONTRALMIRANTE VILLAR,ZORRITOS,5) Fibra Óptica,Comercial,1
157309,2025-12-01,INTERNEXA PERU S.A.,UCAYALI,CORONEL PORTILLO,CALLERIA,5) Fibra Óptica,Comercial,2

In [34]:
ruta_41 = archivos["4.1 Telefonía Fija"]
vista_41 = pd.read_excel(
    ruta_41,
    sheet_name="Dataset",
    header=None,
    nrows=10
)
vista_41

,0,1,2,3,4,5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,DATASET: LÍNEAS FIJAS DE ABONADO EN SERVICIO,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Empresa,Departamento,Medio de Acceso,Mes,Líneas
4,NaN,TELEFONICA DEL PERU S.A.A.,NaN,NaN,1991-12-01 00:00:00,585864
5,NaN,TELEFONICA DEL PERU S.A.A.,NaN,NaN,1992-12-01 00:00:00,604603
6,NaN,TELEFONICA DEL PERU S.A.A.,NaN,NaN,1993-12-01 00:00:00,664989
7,NaN,TELEFONICA DEL PERU S.A.A.,NaN,NaN,1994-12-01 00:00:00,759191
8,NaN,TELEFONICA DEL PERU S.A.A.,NaN,NaN,1995-12-01 00:00:00,1088176
9,NaN,TELEFONICA DEL PERU S.A.A.,NaN,NaN,1996-01-01 00:00:00,1071517

In [35]:
diccionario_41 = pd.read_excel(
    ruta_41,
    sheet_name="Diccionario",
    header=None
)
diccionario_41.head(20)

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,ATRIBUTO,DESCRIPCIÓN,TIPO DE DATO
3,NaN,Empresa,Nombre (razón social) de la empresa operadora ...,Cadena
4,NaN,Departamento,Departamento donde se encuentra el teléfono fi...,Cadena
5,NaN,Medio de Acceso,Medio de acceso: Alámbrico o Inalámbrico.,Cadena
6,NaN,Mes,Mes al que corresponde el dato reportado.,Fecha: AAAA-MM-DD
7,NaN,Líneas,Cantidad de líneas fijas de abonado en servicio.,Numérico
8,NaN,"Información a marzo de 2026, actualizada al 21...",NaN,NaN
9,NaN,Nota general: Información remitida por las emp...,NaN,NaN
10,NaN,"A partir de abril de 2025, Telefónica del Perú...",NaN,NaN

In [36]:
df_41 = pd.read_excel(
    ruta_41,
    sheet_name="Dataset",
    header=3
)
df_41 = df_41.loc[:, ~df_41.columns.astype(str).str.startswith("Unnamed")]
df_41.head()

                      Empresa Departamento Medio de Acceso        Mes   Líneas
0  TELEFONICA DEL PERU S.A.A.          NaN             NaN 1991-12-01   585864
1  TELEFONICA DEL PERU S.A.A.          NaN             NaN 1992-12-01   604603
2  TELEFONICA DEL PERU S.A.A.          NaN             NaN 1993-12-01   664989
3  TELEFONICA DEL PERU S.A.A.          NaN             NaN 1994-12-01   759191
4  TELEFONICA DEL PERU S.A.A.          NaN             NaN 1995-12-01  1088176

In [37]:
print("Filas:", df_41.shape[0])
print("Columnas:", df_41.shape[1])
print("\nColumnas:")
for columna in df_41.columns:
    print("-", columna)
print("\nTipos de datos:")
print(df_41.dtypes)

Filas: 52674
Columnas: 5

Columnas:
- Empresa
- Departamento
- Medio de Acceso
- Mes
- Líneas

Tipos de datos:
Empresa                    object
Departamento               object
Medio de Acceso            object
Mes                datetime64[ns]
Líneas                      int64
dtype: object

In [38]:
print("Fecha mínima:", df_41["Mes"].min())
print("Fecha máxima:", df_41["Mes"].max())
print("\nValores nulos:")
print(df_41.isnull().sum())

Fecha mínima: 1991-12-01 00:00:00
Fecha máxima: 2026-03-01 00:00:00

Valores nulos:
Empresa                0
Departamento          90
Medio de Acceso    13155
Mes                    0
Líneas                 0
dtype: int64

In [39]:
print("Duplicados exactos:", df_41.duplicated().sum())

Duplicados exactos: 21

In [40]:
for columna in [
    "Empresa",
    "Departamento",
    "Medio de Acceso"
]:
    print(f"{columna}: {df_41[columna].nunique()} valores únicos")

Empresa: 48 valores únicos
Departamento: 26 valores únicos
Medio de Acceso: 5 valores únicos

In [41]:
df_41.tail()

,Empresa,Departamento,Medio de Acceso,Mes,Líneas
52669,WOW TEL S.A.C.,SAN MARTIN,Alámbrico,2026-03-01,707
52670,WOW TEL S.A.C.,TACNA,Alámbrico,2026-03-01,1384
52671,WOW TEL S.A.C.,TUMBES,Alámbrico,2026-03-01,1074
52672,WOW TEL S.A.C.,UCAYALI,Alámbrico,2026-03-01,1040
52673,YACHAY TELECOMUNICACIONES S.A.C.,LIMA,Alámbrico,2026-03-01,14

In [42]:
import os
salida = "/home/nevado/BigData_UPAO/osiptel_staging/csv_raw"
os.makedirs(salida, exist_ok=True)
df_21.to_csv(
    f"{salida}/internet_fijo_2_1.csv",
    index=False,
    encoding="utf-8"
)
df_22.to_csv(
    f"{salida}/fibra_optica_2_2.csv",
    index=False,
    encoding="utf-8"
)
df_23.to_csv(
    f"{salida}/internet_fijo_distrital_2_3.csv",
    index=False,
    encoding="utf-8"
)
df_41.to_csv(
    f"{salida}/telefonia_fija_4_1.csv",
    index=False,
    encoding="utf-8"
)
print("CSV generados correctamente")

CSV generados correctamente